name: Run eCourts Causelist Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests beautifulsoup4

      - name: Install Playwright browsers
        run: |
          playwright install chromium --with-deps

      - name: Run scraper script
        run: |
          python ecourts_causelist_scraper.py

      - name: List results
        run: |
          echo "=== causelists directory ==="
          ls -lah causelists || echo "No files found."

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: causelists-artifact
          path: causelists/
          if-no-files-found: warn
