name: Run eCourts Causelist Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper script
        run: |
          python ecourts_causelist_scraper.py

      - name: List causelists directory (for logs)
        run: |
          echo "=== causelists contents ==="
          ls -lah causelists || echo "No files in causelists/"

      - name: Upload causelists artifact
        uses: actions/upload-artifact@v4
        with:
          name: causelists-artifact
          path: causelists/
          if-no-files-found: warn
